# Generated by Django 5.0.3 on 2025-05-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_data',
            field=models.BinaryField(blank=True, default=bytes, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
