#!/bin/bash

psql -U recuser -d recdb <<-EOSQL
    CREATE USER $REC_JDBC_USERNAME WITH PASSWORD '$STORE_JDBC_PASSWORD';
    CREATE DATABASE sonar OWNER $SONAR_JDBC_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE sonar TO $SONAR_JDBC_USERNAME;
EOSQL